language: php

php:
  - 5.3
  - 5.4
  - 5.5
  # 5.6 is tested using composer install
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TRANSPORT=jackrabbit COMPOSER_INSTALL=1
    - php: 5.6
      env: TRANSPORT=doctrine_dbal COMPOSER_INSTALL=1

env:
  - TRANSPORT=jackrabbit
  - TRANSPORT=doctrine_dbal

before_install:
  - composer self-update
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi

install: if [ "$COMPOSER_INSTALL" != "1" ]; then composer update --no-scripts --prefer-dist; else composer install --no-scripts --prefer-dist; fi

before_script:
  - cp app/config/phpcr_${TRANSPORT}.yml.dist app/config/phpcr.yml
  - composer run-script post-update-cmd
  - ./app/tests/travis_${TRANSPORT}.sh
  - app/console doctrine:phpcr:workspace:create sandbox_test -e=test
  - app/console doctrine:phpcr:repository:init -e=test

script: phpunit -c app

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
